# Generated by Django 3.2.2 on 2022-03-20 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usruploads',
            name='upload_dir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.usr_dirs'),
        ),
    ]
